// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	model "github.com/GuoxinL/snowflake-gorm/nodeid/gorm/model"
)

func newSnowflakeKv(db *gorm.DB, opts ...gen.DOOption) snowflakeKv {
	_snowflakeKv := snowflakeKv{}

	_snowflakeKv.snowflakeKvDo.UseDB(db, opts...)
	_snowflakeKv.snowflakeKvDo.UseModel(&model.SnowflakeKv{})

	tableName := _snowflakeKv.snowflakeKvDo.TableName()
	_snowflakeKv.ALL = field.NewAsterisk(tableName)
	_snowflakeKv.Key = field.NewString(tableName, "key")
	_snowflakeKv.NodeID = field.NewInt64(tableName, "node_id")
	_snowflakeKv.Time = field.NewInt64(tableName, "time")
	_snowflakeKv.Created = field.NewTime(tableName, "created")
	_snowflakeKv.Updated = field.NewTime(tableName, "updated")

	_snowflakeKv.fillFieldMap()

	return _snowflakeKv
}

type snowflakeKv struct {
	snowflakeKvDo snowflakeKvDo

	ALL     field.Asterisk
	Key     field.String // Key
	NodeID  field.Int64  // Node ID
	Time    field.Int64  // time
	Created field.Time   // 创建时间
	Updated field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (s snowflakeKv) Table(newTableName string) *snowflakeKv {
	s.snowflakeKvDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s snowflakeKv) As(alias string) *snowflakeKv {
	s.snowflakeKvDo.DO = *(s.snowflakeKvDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *snowflakeKv) updateTableName(table string) *snowflakeKv {
	s.ALL = field.NewAsterisk(table)
	s.Key = field.NewString(table, "key")
	s.NodeID = field.NewInt64(table, "node_id")
	s.Time = field.NewInt64(table, "time")
	s.Created = field.NewTime(table, "created")
	s.Updated = field.NewTime(table, "updated")

	s.fillFieldMap()

	return s
}

func (s *snowflakeKv) WithContext(ctx context.Context) *snowflakeKvDo {
	return s.snowflakeKvDo.WithContext(ctx)
}

func (s snowflakeKv) TableName() string { return s.snowflakeKvDo.TableName() }

func (s snowflakeKv) Alias() string { return s.snowflakeKvDo.Alias() }

func (s snowflakeKv) Columns(cols ...field.Expr) gen.Columns { return s.snowflakeKvDo.Columns(cols...) }

func (s *snowflakeKv) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *snowflakeKv) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 5)
	s.fieldMap["key"] = s.Key
	s.fieldMap["node_id"] = s.NodeID
	s.fieldMap["time"] = s.Time
	s.fieldMap["created"] = s.Created
	s.fieldMap["updated"] = s.Updated
}

func (s snowflakeKv) clone(db *gorm.DB) snowflakeKv {
	s.snowflakeKvDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s snowflakeKv) replaceDB(db *gorm.DB) snowflakeKv {
	s.snowflakeKvDo.ReplaceDB(db)
	return s
}

type snowflakeKvDo struct{ gen.DO }

func (s snowflakeKvDo) Debug() *snowflakeKvDo {
	return s.withDO(s.DO.Debug())
}

func (s snowflakeKvDo) WithContext(ctx context.Context) *snowflakeKvDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s snowflakeKvDo) ReadDB() *snowflakeKvDo {
	return s.Clauses(dbresolver.Read)
}

func (s snowflakeKvDo) WriteDB() *snowflakeKvDo {
	return s.Clauses(dbresolver.Write)
}

func (s snowflakeKvDo) Session(config *gorm.Session) *snowflakeKvDo {
	return s.withDO(s.DO.Session(config))
}

func (s snowflakeKvDo) Clauses(conds ...clause.Expression) *snowflakeKvDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s snowflakeKvDo) Returning(value interface{}, columns ...string) *snowflakeKvDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s snowflakeKvDo) Not(conds ...gen.Condition) *snowflakeKvDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s snowflakeKvDo) Or(conds ...gen.Condition) *snowflakeKvDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s snowflakeKvDo) Select(conds ...field.Expr) *snowflakeKvDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s snowflakeKvDo) Where(conds ...gen.Condition) *snowflakeKvDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s snowflakeKvDo) Order(conds ...field.Expr) *snowflakeKvDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s snowflakeKvDo) Distinct(cols ...field.Expr) *snowflakeKvDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s snowflakeKvDo) Omit(cols ...field.Expr) *snowflakeKvDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s snowflakeKvDo) Join(table schema.Tabler, on ...field.Expr) *snowflakeKvDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s snowflakeKvDo) LeftJoin(table schema.Tabler, on ...field.Expr) *snowflakeKvDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s snowflakeKvDo) RightJoin(table schema.Tabler, on ...field.Expr) *snowflakeKvDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s snowflakeKvDo) Group(cols ...field.Expr) *snowflakeKvDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s snowflakeKvDo) Having(conds ...gen.Condition) *snowflakeKvDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s snowflakeKvDo) Limit(limit int) *snowflakeKvDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s snowflakeKvDo) Offset(offset int) *snowflakeKvDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s snowflakeKvDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *snowflakeKvDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s snowflakeKvDo) Unscoped() *snowflakeKvDo {
	return s.withDO(s.DO.Unscoped())
}

func (s snowflakeKvDo) Create(values ...*model.SnowflakeKv) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s snowflakeKvDo) CreateInBatches(values []*model.SnowflakeKv, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s snowflakeKvDo) Save(values ...*model.SnowflakeKv) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s snowflakeKvDo) First() (*model.SnowflakeKv, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SnowflakeKv), nil
	}
}

func (s snowflakeKvDo) Take() (*model.SnowflakeKv, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SnowflakeKv), nil
	}
}

func (s snowflakeKvDo) Last() (*model.SnowflakeKv, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SnowflakeKv), nil
	}
}

func (s snowflakeKvDo) Find() ([]*model.SnowflakeKv, error) {
	result, err := s.DO.Find()
	return result.([]*model.SnowflakeKv), err
}

func (s snowflakeKvDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SnowflakeKv, err error) {
	buf := make([]*model.SnowflakeKv, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s snowflakeKvDo) FindInBatches(result *[]*model.SnowflakeKv, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s snowflakeKvDo) Attrs(attrs ...field.AssignExpr) *snowflakeKvDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s snowflakeKvDo) Assign(attrs ...field.AssignExpr) *snowflakeKvDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s snowflakeKvDo) Joins(fields ...field.RelationField) *snowflakeKvDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s snowflakeKvDo) Preload(fields ...field.RelationField) *snowflakeKvDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s snowflakeKvDo) FirstOrInit() (*model.SnowflakeKv, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SnowflakeKv), nil
	}
}

func (s snowflakeKvDo) FirstOrCreate() (*model.SnowflakeKv, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SnowflakeKv), nil
	}
}

func (s snowflakeKvDo) FindByPage(offset int, limit int) (result []*model.SnowflakeKv, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s snowflakeKvDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s snowflakeKvDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s snowflakeKvDo) Delete(models ...*model.SnowflakeKv) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *snowflakeKvDo) withDO(do gen.Dao) *snowflakeKvDo {
	s.DO = *do.(*gen.DO)
	return s
}
