// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSnowflakeKv = "snowflake_kv"

// SnowflakeKv mapped from table <snowflake_kv>
type SnowflakeKv struct {
	Key     string     `gorm:"column:key;primaryKey;comment:Key" json:"key"`                                                          // Key
	NodeID  int64      `gorm:"column:node_id;not null;uniqueIndex:snowflake_kv_UN_node_id,priority:1;comment:Node ID" json:"node_id"` // Node ID
	Time    int64      `gorm:"column:time;not null;comment:time" json:"time"`                                                         // time
	Created *time.Time `gorm:"column:created;not null;comment:创建时间" json:"created"`                                                   // 创建时间
	Updated time.Time  `gorm:"column:updated;not null;comment:更新时间" json:"updated"`                                                   // 更新时间
}

// TableName SnowflakeKv's table name
func (*SnowflakeKv) TableName() string {
	return TableNameSnowflakeKv
}
